# configuration for pre-commit git hooks
ci:
  autofix_prs: false # disable autofixing PRs

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff # Linter
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format # Formatter
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.1
    hooks:
      - id: uv-lock
